version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: oxo-db
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: 2kNXsF3Pawji
      POSTGRES_DB: verceldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
